language: python
sudo: required

python:
  - "2.7"


addons:
  apt:
    packages:
    - libpq-dev
    - python-dev
    - psycopg2

install:
  - "pip install -r requirements.txt --allow-external ripe.atlas.sagan ripe.atlas.cousteau"

before_script:
  - mv simon-web/simon_project/passwords_dummy.py simon-web/simon_project/passwords.py

script:
  - python simon-web/manage.py test
