language: python
sudo: required

python:
  - "2.7"

services:
  - postgresql

addons:
  code_climate:
    repo_token: f7fa84853f7688638c4692deda36f9c85b4c4099fd42da5a6e7097c2f29cd651
  apt:
    packages:
    - libpq-dev
    - python-dev
    - python-psycopg2

install:
  - "pip install -r requirements.txt --allow-external ripe.atlas.sagan ripe.atlas.cousteau"

before_script:
  - mv simon-web/simon_project/passwords_dummy.py simon-web/simon_project/passwords.py
  - psql -c 'create database simon;' -U postgres

script:
  - python simon-web/manage.py test
