language: python

python:
  - "2.7"

install: "pip install -r requirements.txt --allow-external ripe.atlas.sagan ripe.atlas.cousteau"

before_script:
  - apt-get install libpq-dev python-dev
  - mv simon-web/simon_project/passwords_dummy.py simon-web/simon_project/passwords.py

script:
  - python simon-web/manage.py test
