language: python

python:
  - "2.7"

install: "pip install -r requirements.txt --allow-external ripe.atlas.sagan ripe.atlas.cousteau"

before_script:
  - touch simon-web/passwords.py

script:
  - python simon-web/manage.py test
