language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --allow-external ripe.atlas.sagan ripe.atlas.cousteau"
script:
  - python simon-web/manage.py test
