language: python

python:
  - "2.7"

install: "pip install -r requirements.txt --allow-external ripe.atlas.sagan ripe.atlas.cousteau"

before_script:
  - export EMAIL_HOST='smtp.gmail.com'
  - export EMAIL_PORT=587
  - export EMAIL_HOST_USER=''
  - export EMAIL_HOST_PASSWORD=''
  - export SERVER_EMAIL=''
  - export DEFAULT_FROM_EMAIL=""
  - export DBNAME='simon'
  - export DBUSER=''
  - export DBPASSWORD=''
  - export DBHOST='127.0.0.1'
  - export DBPORT='5432'
  - export PROBEAPI=""
  - export TWITTER={}

script:
  - python simon-web/manage.py test
