# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-07 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 2, 4, 308710)),
        ),
        migrations.AlterField(
            model_name='httpscheck',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 2, 4, 302622)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 2, 4, 305135)),
        ),
        migrations.AlterField(
            model_name='results',
            name='date_test',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 2, 4, 294504), verbose_name=b'test date'),
        ),
        migrations.AlterField(
            model_name='ripeatlasmonitoredids',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 2, 4, 308165)),
        ),
        migrations.AlterField(
            model_name='ripeatlastoken',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 2, 4, 307345)),
        ),
        migrations.AlterField(
            model_name='ripeatlastokenlist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 2, 4, 307803)),
        ),
    ]
