# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0001_squashed_0007_auto_20201008_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeapirequest',
            name='test_settings',
            field=models.TextField(default=b'{}', help_text=b'JSON request as a text field. This should be JSONField in higher versions of PostgreSQL'),
        ),
    ]
