# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-07 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0002_auto_20201007_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RipeAtlasMeasurement',
        ),
        migrations.DeleteModel(
            name='RipeAtlasMonitoredIds',
        ),
        migrations.RemoveField(
            model_name='ripeatlaspingresult',
            name='ripeatlasresult_ptr',
        ),
        migrations.RemoveField(
            model_name='ripeatlasresult',
            name='results_ptr',
        ),
        migrations.RemoveField(
            model_name='ripeatlastoken',
            name='probe',
        ),
        migrations.DeleteModel(
            name='RipeAtlasTokenList',
        ),
        migrations.RemoveField(
            model_name='ripeatlastracerouteresult',
            name='ripeatlasresult_ptr',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 7, 15, 227280)),
        ),
        migrations.AlterField(
            model_name='httpscheck',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 7, 15, 221240)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 7, 15, 224801)),
        ),
        migrations.AlterField(
            model_name='results',
            name='date_test',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 7, 15, 214730), verbose_name=b'test date'),
        ),
        migrations.DeleteModel(
            name='RipeAtlasPingResult',
        ),
        migrations.DeleteModel(
            name='RipeAtlasResult',
        ),
        migrations.DeleteModel(
            name='RipeAtlasToken',
        ),
        migrations.DeleteModel(
            name='RipeAtlasTracerouteResult',
        ),
    ]
