# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-22 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0003_probeapipingresult_probeapi_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probeapipingresult',
            old_name='probeapi_id',
            new_name='probeapi_probe_id',
        ),
    ]
