# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0004_auto_20201122_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeapirequest',
            name='test_type',
            field=models.CharField(default=b'ping', max_length=16),
        ),
    ]
