# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0005_probeapirequest_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeapiTracerouteHop',
            fields=[
                ('probeapipingresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simon_app.ProbeApiPingResult')),
                ('traceroute_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simon_app.TracerouteResult')),
            ],
            bases=('simon_app.probeapipingresult',),
        ),
    ]
