# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0005_auto_20201008_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpscheck',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 3, 52, 26, 915980)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 3, 52, 26, 918832)),
        ),
        migrations.AlterField(
            model_name='results',
            name='date_test',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 3, 52, 26, 909504), verbose_name=b'test date'),
        ),
    ]
