# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0006_auto_20201008_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeApiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_1', models.DateTimeField(default=datetime.datetime.now, help_text=b'Datetime this test was requested to the platform')),
                ('date_2', models.DateTimeField(default=datetime.datetime.now, help_text=b'Last datetime this results was requested from the platform')),
                ('probeapi_id', models.CharField(max_length=1024)),
                ('reply_1', models.TextField(help_text=b'JSON payload as a text field. This should be JSONField in higher versions of PostgreSQL')),
                ('reply_2', models.TextField(help_text=b'JSON payload as a text field. This should be JSONField in higher versions of PostgreSQL')),
                ('stage_requested', models.BooleanField(default=False, help_text=b'Determines is a test results has already been collected from the ProbePAI platform')),
                ('stage_collected', models.BooleanField(default=False, help_text=b'Determines is a test results has already been collected from the ProbePAI platform')),
            ],
        ),
        migrations.AlterField(
            model_name='httpscheck',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 3, 55, 6, 843813)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 3, 55, 6, 846329)),
        ),
        migrations.AlterField(
            model_name='results',
            name='date_test',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 3, 55, 6, 838324), verbose_name=b'test date'),
        ),
    ]
