# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0006_probeapitraceroutehop'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeapitraceroutehop',
            name='hop_number',
            field=models.IntegerField(default=0, help_text=b'0 means something went wrong'),
        ),
    ]
