# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0007_probeapitraceroutehop_hop_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeapiTracerouteResult',
            fields=[
                ('tracerouteresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simon_app.TracerouteResult')),
            ],
            bases=('simon_app.tracerouteresult',),
        ),
        migrations.AlterField(
            model_name='probeapitraceroutehop',
            name='traceroute_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simon_app.ProbeapiTracerouteResult'),
        ),
    ]
