# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0009_auto_20210426_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeApiFetchFromFTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_time', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('charging', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('acc', models.IntegerField()),
                ('network_operator', models.CharField(max_length=64)),
                ('sim_operator', models.CharField(max_length=64)),
                ('cellular_type', models.CharField(max_length=64)),
                ('timestamp', models.BigIntegerField()),
                ('active_connection', models.CharField(max_length=64)),
                ('device_info', models.CharField(max_length=128)),
                ('package_name', models.CharField(max_length=128)),
                ('command_result', models.TextField()),
                ('command_name', models.TextField()),
                ('unique_id', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('os_version', models.CharField(max_length=64)),
            ],
        )
    ]
