# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('simon_app', '0011_auto_20211209_1045'), ('simon_app', '0012_auto_20211221_0923'), ('simon_app', '0013_auto_20211221_0925')]

    dependencies = [
        ('simon_app', '0010_auto_20211122_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probeapi_batch', models.CharField(max_length=10)),
                ('fecha_de_ejecucion', models.DateTimeField()),
                ('probeapi_batch_fecha', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'IP', b'In progress'), (b'ER', b'Error'), (b'FI', b'Finished')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='probeapifetchfromftp',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simon_app.HourlyBatch'),
        ),
    ]
