# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-21 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0011_auto_20211209_1045_squashed_0013_auto_20211221_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlybatch',
            name='fecha_de_ejecucion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
