# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0014_auto_20211221_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='network_operator',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
