# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0015_auto_20211222_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='sim_operator',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
