# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0018_auto_20211222_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='acc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='active_connection',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='charging',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='device_info',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='os_version',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='package_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='probeapifetchfromftp',
            name='version',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
