# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0019_auto_20220223_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='ave_rtt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='dev_rtt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='max_rtt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='median_rtt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='min_rtt',
            field=models.FloatField(null=True),
        ),
    ]
