# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0023_auto_20220324_0547'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='probeapiv3metadataresult',
        #     name='probeapifetchfromftp',
        # ),
        # migrations.AddField(
        #     model_name='probeapiv3pingresult',
        #     name='probeapifetchfromftp',
        #     field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simon_app.ProbeApiFetchFromFTP'),
        # ),
    ]
