# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-25 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0024_auto_20220324_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeApiV3ResultMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probeapi_probe_id', models.CharField(default=b'', max_length=128)),
                ('hostname', models.CharField(default=b'', max_length=128, null=True)),
                ('ipv4only', models.BooleanField(default=False)),
                ('ipv6only', models.BooleanField(default=False)),
                ('error_msg', models.CharField(default=b'', max_length=128, null=True)),
                ('server_time', models.DateTimeField(default=datetime.datetime.now)),
                ('time_diff', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProbeApiV3TracerouteHop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simon_app.ProbeApiV3DataResult')),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='probeapiv3pingresult',
        #     name='probeapifetchfromftp',
        # ),
        migrations.CreateModel(
            name='ProbeApiV3PingResultMetaData',
            fields=[
                ('probeapiv3resultmetadata_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='simon_app.ProbeApiV3ResultMetaData')),
            ],
            bases=('simon_app.probeapiv3resultmetadata',),
        ),
        migrations.AlterField(
            model_name='probeapiv3pingresult',
            name='metadata',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_obj', to='simon_app.ProbeApiV3PingResultMetaData'),
        ),

        migrations.CreateModel(
            name='ProbeApiV3TracerouteResultMetaData',
            fields=[
                ('probeapiv3resultmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simon_app.ProbeApiV3ResultMetaData')),
            ],
            bases=('simon_app.probeapiv3resultmetadata',),
        ),
        migrations.DeleteModel(
            name='ProbeApiV3MetaDataResult',
        ),
        migrations.AddField(
            model_name='probeapiv3resultmetadata',
            name='probeapifetchfromftp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='simon_app.ProbeApiFetchFromFTP'),
        ),
        migrations.AddField(
            model_name='probeapiv3traceroutehop',
            name='traceroute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='simon_app.ProbeApiV3TracerouteResultMetaData'),
        ),
    ]
