# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-25 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0025_auto_20220325_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probeapiv3resultmetadata',
            name='probeapifetchfromftp',
        ),
        migrations.AddField(
            model_name='probeapiv3pingresultmetadata',
            name='probeapifetchfromftp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pingmetadata', to='simon_app.ProbeApiFetchFromFTP'),
        ),
        migrations.AddField(
            model_name='probeapiv3tracerouteresultmetadata',
            name='probeapifetchfromftp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traceroutemetadata', to='simon_app.ProbeApiFetchFromFTP'),
        ),
    ]
