# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-04 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon_app', '0026_auto_20220325_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeapiv3traceroutehop',
            name='hop_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
